blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # post views
    url(r'^$', views.post_index, name='post_index'),
    url(r'^blog/$', views.post_list, name='post_list'), # askjola
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^askjola/$', views.askjola, name='askjola'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',views.post_detail,name='post_detail'),
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls',namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from .utils import mentee_sender
from django.db.models.signals import pre_save

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Profile(models.Model):
	OWNER_STATUS = (
	    ('owner', 'Owner'),
	    ('staff', 'Staff'),
	)
	owner = models.OneToOneField(User)
	background_pic = models.ImageField(upload_to="me/",null=True,blank=True)
	profile_pic = models.ImageField(upload_to='me/',null=True,blank=True)
	owner_status = models.CharField(max_length=300,choices=OWNER_STATUS,default='staff')

	def __str__(self):
		return str(self.owner)

class Post(models.Model):
	STATUS_CHOICES = (
	    ('draft', 'Draft'),
	    ('published', 'Published'),
	)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, related_name='blog_posts')
	body = models.TextField()
	header_pic = models.ImageField(upload_to="",blank=True,null=True)
	heade_pic_descr = models.CharField(max_length=200,blank=True,null=True)
	topic_pic = models.ImageField(upload_to="users/%Y/%m/%d",blank=True,null=True)
	topic_pic_descr = models.CharField(max_length=200,blank=True,null=True)
	topic_pic_2 = models.ImageField(upload_to="users/%Y/%m/%d",blank=True,null=True)
	topic_pic_2_descr = models.CharField(max_length=200,blank=True,null=True)
	topic_pic_3 = models.ImageField(upload_to="users/%Y/%m/%d",blank=True,null=True)
	topic_pic_3_descr = models.CharField(max_length=200,blank=True,null=True,)
	topic_pic_4 = models.ImageField(upload_to="users/%Y/%m/%d",blank=True,null=True)
	topic_pic_4_descr = models.CharField(max_length=200,blank=True,null=True)
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
	page_views = models.IntegerField(default=0)
	objects = models.Manager() # The default manager.
	published = PublishedManager() # The Dahl-specific manager.

    #tags = TaggableManager()

	class Meta:
	    ordering = ('-publish',)

	def __str__(self):
	    return self.title

	def get_absolute_url(self):
	    return reverse('blog:post_detail', args=[self.publish.year,
	                                             self.publish.strftime('%m'),
	                                             self.publish.strftime('%d'),
	                                             self.slug])

class Mentee(models.Model):
	name = models.CharField(max_length=200)
	phone_number = models.IntegerField()
	email_field = models.EmailField()
	createdate = models.DateTimeField(auto_now_add=True,blank=True,null=True)

	def __str__(self):
		return self.name

class AskJola(models.Model):
	name = models.CharField(max_length=200)
	email_state = models.EmailField()
	body = models.TextField()

	def __str__(self):
		return self.name

		
class Ads(models.Model):
	url = models.CharField(max_length=200)
	banner = models.ImageField('ads/',blank=True,null=True)

	def __str__(self):
		return self.url

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    mentee_sender(instance,Mentee.objects.all())



pre_save.connect(pre_save_post_receiver, sender=Post)

blog/forms.py
from django import forms
from .models import Mentee,AskJola

class feedBackForm(forms.ModelForm):
	class Meta:
		model = Mentee
		fields = ('name','phone_number','email_field')

class AskJolaForm(forms.ModelForm):
	class Meta:
		model = AskJola
		fields = ('name','email_state','body')

blog/views.py
#from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post,Ads,Profile,Mentee
from .forms import feedBackForm,AskJolaForm
from django.http import HttpResponse
from django.core.mail import send_mail
# Create your views here.

def post_index(request):
  ad = Ads.objects.order_by('?')[0:1]
  blog = Post.objects.all()[:3]
  return render(request, 'post/index.html', {'ads':ad,'object_list':blog})


def post_list(request):
    ad = Ads.objects.order_by('?')[0:1]
    object_list = Post.published.all()
    profile = Profile.objects.get(owner_status='owner')
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'post/list.html', {'page': page,
                                                   'posts': posts,'ads':ad,'profile':profile})

def post_detail(request, year, month, day, post):
    ad = Ads.objects.order_by('?')[0:1]
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    if request.method == 'GET':
      post.page_views += 1
      post.save()
    return render(request, 'post/detail.html', {'post': post,'ads':ad})

def feedback(request):
    if request.method != 'POST':
      form = feedBackForm()
    else:
      form = feedBackForm(request.POST,request.FILES or None)
      if form.is_valid():
        form.save()
    return HttpResponse('ok')

def askjola(request):
    if request.method != 'POST':
      form = AskJolaForm()
    else:
      form = AskJolaForm(request.POST,request.FILES or None)
      if form.is_valid():
        form.save()
    return HttpResponse('ok')

    #send_mail(subject,message,from_email,reciever_list,fail_silently=False,html_message=html_message)

blog/templates/_forms.html
{% load bootstrap3 %}
{% load static %}
<form method="POST" action="/feedback/" id="wo">
        {% csrf_token %}
        {% bootstrap_form form %}
     <input type="submit" id='uploadSubmit' value="submit" class="btn btn-default btn-block"> {{ path}}
   <div class="loa text-center" style="display: none;">
        <img src="{% static 'loading.gif' %}">
    </div>
</form>
<script type="text/javascript">
// $('#id_url_locator').val('' + '{{ url }}')
$('#wo').on('submit', function(e){
    e.preventDefault();
    var fd = new FormData(document.querySelector("form#wo"));
    $.ajax({
            url: '/feedback/',
            type: 'POST',
            data: fd,
            processData: false,  // tell jQuery not to process the data
            contentType: false,   // tell jQuery not to set contentType
        beforeSend: function () {
            $('#id_content').val('');
            $('#feelings').val('');
            // $('#wo').html('<img src="{% static 'img/loading.gif' %}">');
        },

        error : function(){
            $('.feedback-loop').html("<div class='text-center'><h1 class='danger'><span class='glyphicon glyphicon-remove' aria-hidden='true'></span></h1> An inernal server error occured</div>")
        },

        success : function(){
            $('.loa').hide();
            $('.feedback-loop').html("<div class='text-center'><h1 class='success'><span class='glyphicon glyphicon-ok' aria-hidden='true'></span></h1> Thanks for being a mentee you will recieve daily tips on being a better leader</div>")
        }

    });
});
</script>

blog/templates/ask_forms.html
{% load bootstrap3 %}
{% load static %}
<form method="POST" action="/askjola/" id="work">
        {% csrf_token %}
        {% bootstrap_form form %}
     <input type="submit" id='uploadSubmit' value="submit" class="btn btn-default btn-block"> {{ path}}
   <div class="loa text-center" style="display: none;">
        <img src="{% static 'loading.gif' %}">
    </div>
</form>
<script type="text/javascript">
// $('#id_url_locator').val('' + '{{ url }}')
$('#work').on('submit', function(e){
    e.preventDefault();
    var fd = new FormData(document.querySelector("form#work"));
    $.ajax({
            url: '/askjola/',
            type: 'POST',
            data: fd,
            processData: false,  // tell jQuery not to process the data
            contentType: false,   // tell jQuery not to set contentType
        beforeSend: function () {
            $('#id_content').val('');
            $('#feelings').val('');
            // $('#wo').html('<img src="{% static 'img/loading.gif' %}">');
        },

        error : function(){
            $('.feedback-lop').html("<div class='text-center'><h1 class='danger'><span class='glyphicon glyphicon-remove' aria-hidden='true'></span></h1> An inernal server error occured</div>")
        },

        success : function(){
            $('.loa').hide();
            $('.feedback-lop').html("<div class='text-center'><h1 class='success'><span class='glyphicon glyphicon-ok' aria-hidden='true'></span></h1> Thanks for being a mentee you will recieve daily tips on being a better leader</div>")
        }

    });
});
</script>

blog/templates/base.html
<!doctype html>
{% load static %}
{% load feedback %}
<html>
<head>
  <title>Jola Tankoka - The Official Website of Jola Tankoka</title>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<style type="text/css">
.face {
  color: #0085ff;
}
.twitt {
  color: #17a6ff;
}
  .share_link {
    text-decoration: none;
  }
  body {
    background-color: #eee;
    font-weight: 300;
  }
  h1,h2,h3,h4,h5 {
    font-weight: 300;
  }
  .navbar-default {
    background-color: white;
    border-radius: 0px;
    border-bottom-color: #ddd;
    border-bottom-width: 1px;
}
.navbar-default .navbar-nav > li > a{
    color: #ccc;
}
.navbar-default .navbar-nav > .active > a{
    background-color: transparent;
    color: #FFF;
    padding-bottom: 10px;
    border-bottom: 5px solid black;
}
.navbar-default .navbar-nav > li > a,
.navbar-default .navbar-nav > li > a:hover {
    color: #ccc;
    -webkit-transition: all 150ms ease-in-out;
    -moz-transition: all 150ms ease-in-out;
    -ms-transition: all 150ms ease-in-out;
    -o-transition: all 150ms ease-in-out;
    transition: all 150ms ease-in-out;
}
.navbar-default .navbar-nav > .active > a {
    background-color: transparent;
    color: black;
    padding-bottom: 0.62em;
    border-bottom: 0.45em solid black;
}
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > li > a:hover {
    background-color: transparent;
    color: black;
    padding-bottom: 0.62em;
    border-bottom: 0.45em solid black;
}
@media(max-width:767px){
    .navbar-default .navbar-nav > .active > a {
        border-bottom: none;
        border-left: 0.45em solid black;
        padding-left: 0.5em;
        border-bottom: none;
    }
    .navbar-default .navbar-nav > .active > a:hover,
    .navbar-default .navbar-nav > li > a:hover {
        background-color: transparent;
        color: black;
        padding-bottom: 0.62em;
        border-bottom: none;
        border-left: 0.45em solid black;
        padding-left: 0.5em;
    }
}
.panel {
    margin-bottom: 3px;
    background-color: #fff;
    border: 0;
    border-radius: 0;
    -webkit-box-shadow: 0;
    box-shadow: 0 ; 
}

.main {
    margin-top: 70px;
  }
  .spn {
    margin-right: 5px;
    margin-left: 5px;
  }
  .navbar-nav {
    background-color: transparent !important;
  }
  .spav {
    margin-left: 15px;
    text-transform: uppercase;
  }
</style>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
      <div class="navbar-header">
      <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" style="height: 25px;"></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <i class="fa fa-bars"></i>
                <b>Menu</b>
            </button>
            
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav" style="margin-right: -10px;">
                <li class="{% block aks %}{% endblock%} spav">
                  <a href="#myQuestion" role="button" data-toggle="modal" style="background-color: white;">
                        <i class="fa fa-comments"></i> <b>Ask Jola</b>
                    </a>
                </li>
                <li class="{% block blog %}{% endblock%} spav">
                    <a href="{% url 'blog:post_list' %}" style="background-color: white;">
                        <i class="fa fa-newspaper-o"></i> <b>Blog</b>
                    </a>
                </li>
                 <li class="{% block shop %}{% endblock%} spav">
                    <a href="#" style="background-color: white;">
                        <i class="fa fa-shopping-bag"></i> <b>Shop</b>
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            </ul>
        </div>
        </div>
    </nav>
    <div>
  {% block content %}
  {% endblock %}
</div>
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Become a mentee</h4>
      </div>
      <div class="modal-body feedback-loop">
      <h4>Fill the form and become a mentee</h4>
      <div style="padding: 5px">
      {% report_form %}
      </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myQuestion">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><i class="fa fa-comments"></i> Ask Jola</h4>
      </div>
      <div class="modal-body feedback-lop">
      <div style="padding: 2px">
      {% ask_form %}
      </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

blog/templates/post/detail.html
{% extends 'base.html' %}
{% block blog %}active{% endblock%}
{% block content %}
<div class="main">
	<div class="container">
		<div class="row">
			<div class="col-md-3 hidden-sm hidden-xs">
				<div class="panel panel-default">
					{% if post.author.profile.background_pic %}
					<img src="{{ post.author.profile.background_pic.url }}" style="width: 100%;">
					{% endif %}
					<div class="panel-body">
						<div class="text-center">
					{% if post.author.profile.profile_pic %}
						<img src="{{ post.author.profile.profile_pic.url }}" style="position: relative; width: 45px; height: 45px; top:-30px; margin-bottom: 0px; border-radius: 120px;">
					{% endif %}
					</div>
						<h3 style="margin-top: -25px;">{{ post.author }}</h3>
						<i>Leader, Teacher, Entepreneur</i>

						<div class="text-center">
							<i class="fa fa-facebook-official spn"></i>
							<i class="fa fa-twitter spn"></i>
							<i class="fa fa-linkedin spn"></i>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-body">
						<h2 class="text-center">{{ post.title }}</h2>
						<div class="text-center">
							<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" class="share_link face">
							<i class="fa fa-facebook-official spn"></i>
						</a>
						<a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}" class="share_link twitt">
							<i class="fa fa-twitter spn"></i>
						</a>
						<a href="https://www.linkedin.com/cws/share?url={{ request.build_absolute_uri }}" class="share_link link">
							<i class="fa fa-linkedin spn"></i>
						</a>
						</div>
					</div>

				</div>
				{% if post.header_pic %}
				<div class="panel panel-default">
					<img src="{{ post.header_pic.url }}" style="width: 100%;">
					<div class="panel-body">
						<h5>{{ post.heade_pic_descr }}</h5>
					</div>
				</div>
				{% endif %}
				<div class="visible-sm visible-xs">
					<div class="panel panel-danger">
						<div class="panel-heading">
							Ads
						</div>
							{% for ad in ads %}
								{% if ad.banner %}
								<a href="http://{{ ad.url }}">
									<img src="{{ ad.banner.url }}" style="width: 100%;">
								</a>
								{% endif %}
							{% endfor %}
						</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-body pixel">
						<!-- <h3>{{ post.title }}</h3> -->
						<p>{{ post.body|linebreaks }}</p>
					</div>
				</div>
				{% if post.topic_pic %}
				<div class="panel panel-default">
					<img src="{{ post.topic_pic.url }}" style="width: 100%;">
					<div class="panel-body">
						<h5>{{ post.topic_pic_descr }}</h5>
					</div>
				</div>
				{% endif %}
				{% if post.topic_pic_2 %}
				<div class="panel panel-default">
					<img src="{{ post.topic_pic_2.url }}" style="width: 100%;">
					<div class="panel-body">
						<h5>{{ post.topic_pic_2_descr }}</h5>
					</div>
				</div>
				{% endif %}
				{% if post.topic_pic_3 %}
				<div class="panel panel-default">
					<img src="{{ post.topic_pic_3.url }}" style="width: 100%;">
					<div class="panel-body">
						<h5>{{ post.topic_pic_3_descr }}</h5>
					</div>
				</div>
				{% endif %}
				{% if post.topic_pic_4 %}
				<div class="panel panel-default">
					<img src="{{ post.topic_pic_4.url }}" style="width: 100%;">
					<div class="panel-body">
						<h5>{{ post.topic_pic_4_descr }}</h5>
					</div>
				</div>
				{% endif %}
			</div>
			<div class="col-md-3">
				<div class="panel panel-danger">
				<div class="panel-heading">
					Ads
				</div>
					{% for ad in ads %}
						{% if ad.banner %}
						<a href="http://{{ ad.url }}">
							<img src="{{ ad.banner.url }}" style="width: 100%;">
						</a>
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

    $(".pixel p").each(function(data){
        var urlRegex = /(https?:\/\/[^\s]+)/g;
        var currentHtml = $(this).html();
        var newText;
        newText = currentHtml.replace(urlRegex, '<a href="$1">$1</a>');
        $(this).html(newText);
    })
</script>
{% endblock %}

blog/templates/post/index.html
{% extends 'base.html' %}
{% load static %}
{% block home %}active{% endblock%}
{% block content %}
<style type="text/css">
	.mai {
		background-image: url('static/Leadership-introductiion.jpg');
		background-size: cover;
	    background-position-top: 20px;
	    height: 100vh;
	    margin-top: 0px;
	}
	.colrr {
		padding: 20px;
		background-color: black;
		color: white;
	}
	.bg-1 {
		background-image: url('static/Screenshot_2017-09-26-23-49-33.png');
		background-size: cover;
	    background-position-top: 20px;
	    width: 50%;
	    display: block;
	    margin: 0 !important;
	    padding: 10%
	}
	.bg-1 h1{
		padding-left: 20%;
		padding-right: 20%;
	}
	.bg-1 {
		padding-bottom: 5%;
		height: 400px; 
	}
	.bg-12 {
		background-image: url('static/bus.jpg');
		background-size: cover;
	    background-position-top: 20px;
	    width: 50%;
	    display: block;
	    margin: 0 !important;
	    padding: 10%
	}
	.bg-12 h1{
		padding-left: 20%;
		padding-right: 20%;
	}
	.bg-12 {
		padding-bottom: 5%;
		height: 400px; 
	}
	.posts {
		background-color: black;
	}
	footer {
     background-color: #191919;
     color: #fff;
     /*margin-top: 3em;*/
     padding: 50px;
}
footer h2{
  margin-top: 2em;
  font-weight: bold;
  margin-right: 50px;
}
footer address {
     color: #fff;
   }
   footer ul {
     margin-bottom: 5em;
}
   footer address strong {
     color: #fff;
     display: block;
     padding-bottom: 0.62em;
}
   footer a {
     font-weight: 300;
     color: #fff;
}
footer ul li {
	line-height: 34px;
}
.spacv {
  margin-left: 20px;
  font-size: 20px;
}
.credite {
	background-color: black;
	color: white;
	margin: 0;
	padding: 10px;
	font-size: 20px;
}
	@media (max-width: 705px){
		.bg-1 {
			width: 100%;
		}
		.bg-12 {
			width: 100%;
		}
		h1 {
			margin: 0;
		}
	}
	@media (max-width: 320px){
		h1 {
			font-size: 70px !important;
		}
	}
</style>
<div class="mai text-center">
	<div class="container">
	<h1 style="color: #f5ff7d; padding-top: 20%; font-size: 90px; font-weight: 600;">HEAL. INSPIRE. REVIVE.</h1>

	<p class="text-center" style="font-size: 28px; color: white;">CLOSE THE GAP BETWEEN WHERE YOU ARE TODAY – AND WHERE YOU WANT TO BE.</p>

</div>
</div>
<div class="sign-up-section">
	<div class="col-sm-6 bg-12 text-center">
		<h2 style="color: black;">Do You Want To Improve Your Business Skills</h2>
		<p style="color: gold;"> Get the insight, strategies, and tools you need to take the lead over the competition and drive your business to the next level.</p>
	</div>
<div class="col-sm-6 bg-1 text-center ">
	<h2 style="color: black;">Do You Want To Improve Your Leadership Skills</h2>
	<p style="color: gold;">Are you successful and truly happy, or are there parts of you that are unfulfilled? The extraordinary life you want is within your grasp, but you need clarity and focus to achieve it.</p>
</div>
</div>

<div class="about-me" style="background-color: white;">
	<div class="container">
	<div class="col-sm-6">
		<img src="static/IMG_20170920_234403_667.jpg" style="width: 100%; border-radius: 2000px;">
	</div>
	<div class="col-sm-6" style="margin-top: 80px;">
		<h2>ABOUT JOLA TANKOKA</h2>

<h4><i>World authority on leadership psychology</i></h4>

<p style="font-size: 1.5em;">Jola Tankoka is an entrepreneur, best-selling author, philanthropist and the nation’s #1 Life and Business Strategist. A recognized authority on the psychology of leadership, negotiations and organizational turnaround, he has served as an advisor to leaders around the world for more than 7 years.</p>
	</div>
</div>
</div>
<div class="colrr">
	<div class="container">
	<h2 class="text-center" style="text-transform: uppercase;">Sign Up Here to <a href="#myModal" role="button" data-toggle="modal" class="btn btn-default">Be a Mentee</a></h2>
</div>
</div>

<div class="posts">

	<br>
	<div class="container">
		<h2 class="text-center" style="color: white;">JOLA TANKOKA'S BLOG</h2>
		<br>
		<div class="col-sm-offset-2">
			{% for post in object_list %}
			<div class="col-md-3">
				<div class="panel-default">
					{% if post.header_pic %}
					<!-- <img src="{{ post.header_pic.url }}" style="width: 100%;"> -->
					{% endif %}
					<div class="panel-body" style="background-color: white;">
						<h4>{{ post.title }}</h4>
						<p>{{ post.body|truncatechars:240 }}</p>
						<a href="{{ post.get_absolute_url }}" class="btn btn-danger">Read More →</a>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>


</div>
<footer>
     <div class="container">
	       <div class="col-sm-3">
	         <h2>JT</h2>
	       </div>
	       <div class="col-sm-2 simple">
	         <h5>JOLA TANKOKA</h5>
				<ul class="list-unstyled">
				<li><a href="#">Documentation</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="#">Contact</a></li>
				</ul>
			</div>
			<div class="col-sm-2 simple">
				<h5>Social</h5>
				<ul class="list-unstyled">
				<li><a href="#"><i class="fa fa-facebook-square"></i> Facebook</a></li>
				<li><a href="#"><i class="fa fa-twitter-square"></i> Twitter</a></li>
				<li><a href="#"><i class="fa fa-instagram"></i> Instagram</a></li>
				<li><a href="#"><i class="fa fa-linkedin"></i> Linkedin</a></li>
				</ul> 
			</div>
			<div class="col-sm-2 simple">
				<h5>Support</h5>

				<ul class="list-unstyled">
				<li><a href="#">Contact</a></li>
				<li><a href="#">Terms & conditions</a></li>
				<li><a href="#">Help desk</a></li>
				</ul> 
			</div>
		</div>
		<div class="">
	         <i class="fa fa-facebook-official spacv"></i>
	         <i class="fa fa-twitter spacv"></i>
	         <i class="fa fa-instagram spacv"></i>
	         <i class="fa fa-linkedin spacv"></i>
	       </div>
   </footer>
   <div class="credite">
   		<p class="text-center">&copy 2017 JOLA TANKOKA INTERNATIONAL. CREATED BY OYE.</p>
   </div>
{% endblock %}